services:
  trustcrow-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trustcrowdb
      POSTGRES_USER: postgres
    volumes:
      - trustcrow-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes: 
  trustcrow-db: